# .circleci/config.yml
version: 2.1
orbs:
  macos: circleci/macos@2

jobs:
  iOS:
   macos:
      xcode: 14.1.0
   steps:
     - checkout
     - run: 
        command: xcrun simctl list -j
     - macos/preboot-simulator:
        version: "16.1"
        platform: "iOS"
        device: "iPhone X"
     - run:
        name: Node Version
        command: | 
            nvm install v16.18.1 && nvm alias default 16.18.1
     - run:
        name: Install Appium and Run iOS Test
        command: |
           nvm install v16.18.1 && nvm alias default 16.18.1 
           node -v 
           npm install -g appium@next
           appium -v
           appium driver install xcuitest
           appium plugin install --source npm appium-device-farm
           appium plugin list
           appium driver list
           Platform='iOS' CONFIG_FILE='./configs/iOSConfig.properties' mvn clean -Dtest=Runner test -Dcheckstyle.skip

  Android:
    machine:
      image: android:202102-01
    # To optimize build times, we recommend "large" and above for Android-related jobs
    resource_class: large
    steps:
      - checkout
      - run:
          name: Create avd
          command: |
            SYSTEM_IMAGES="system-images;android-29;default;x86"
            sdkmanager "$SYSTEM_IMAGES"
            echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
      - run:
          name: Launch emulator 1
          command: |
            emulator -avd test -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          background: true

      - run:
          name: wait for emulator
          command: adb wait-for-device shell 'while [[ -z $(getprop dev.bootcomplete) ]]; do sleep 1; done;'
      - run:
          name: Install Appium and Run Android Test
          command: |
            nvm install v16.18.1 && nvm alias default 16.18.1 
            node -v 
            npm install -g appium@next
            appium -v
            appium driver install uiautomator2
            appium plugin install --source npm appium-device-farm
            appium plugin list
            appium driver list
            Platform='android' CONFIG_FILE='./configs/config.properties' mvn clean -Dtest=Runner test -Dcheckstyle.skip


workflows:
  build:
    jobs:
      - iOS
      - Android