# .circleci/config.yml
version: 2.1
jobs:
  iOS: # your job name
    macos:
      xcode: 14.1.0 # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Node Version
          command: | 
            nvm install v16.18.1 && nvm alias default 16.18.1
      - run: 
          name: Simulators
          command: xcrun simctl list

  Android:
    machine:
      image: android:202102-01
    # To optimize build times, we recommend "large" and above for Android-related jobs
    resource_class: large
    steps:
      - checkout
      - run:
          name: Create avd
          command: |
            SYSTEM_IMAGES="system-images;android-29;default;x86"
            sdkmanager "$SYSTEM_IMAGES"
            echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
      - run:
          name: Launch emulator 1
          command: |
            emulator -avd test -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          background: true
          
      - run:
          name: wait for emulator
          command: adb wait-for-device shell 'while [[ -z $(getprop dev.bootcomplete) ]]; do sleep 1; done;'        
      - run:
          name: Install Appium and Run Android Test
          command: |
            nvm install v16.18.1 && nvm alias default 16.18.1 
            node -v 
            npm install -g appium@next
            appium -v
            appium driver install uiautomator2
            appium plugin install --source npm appium-device-farm
            appium plugin list
            appium driver list
            Platform='android' CONFIG_FILE='./configs/config.properties' mvn clean -Dtest=Runner test -Dcheckstyle.skip

            
workflows:
  build:
    jobs:
      - iOS
      - Android